import { createFileRoute } from "@tanstack/react-router";
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell } from "@/components/app-shell";
import { PageHeader, Section } from "@/components/common";
import { analytics } from "@/mock/analytics";

export const Route=createFileRoute("/analytics")({head:()=>({meta:[{title:"Analytics — Nepal Traffic Monitor"},{name:"description",content:"Traffic violation trends and operational distribution charts."},{property:"og:title",content:"Traffic Analytics"},{property:"og:description",content:"Traffic violation trends and operational distribution charts."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:AnalyticsPage});
const tip={background:"var(--popover)",border:"1px solid var(--border)",borderRadius:4};
function ChartBox({title,children}:{title:string;children:React.ReactNode}){return <Section title={title}><div className="h-72 p-4">{children}</div></Section>}
function AnalyticsPage(){return <AppShell><PageHeader title="Analytics" description="Operational patterns from the current demonstration dataset."/><div className="grid gap-5 xl:grid-cols-2"><ChartBox title="Violations by type"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.byType} layout="vertical"><CartesianGrid stroke="var(--border)" horizontal={false}/><XAxis type="number" stroke="var(--muted-foreground)" fontSize={11}/><YAxis type="category" dataKey="name" width={100} stroke="var(--muted-foreground)" fontSize={11}/><Tooltip contentStyle={tip}/><Bar dataKey="value" fill="var(--primary)" radius={[0,2,2,0]}/></BarChart></ResponsiveContainer></ChartBox><ChartBox title="Violations by camera"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.byCamera}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="name" stroke="var(--muted-foreground)" fontSize={11}/><YAxis stroke="var(--muted-foreground)" fontSize={11}/><Tooltip contentStyle={tip}/><Bar dataKey="value" fill="var(--chart-5)" radius={[2,2,0,0]}/></BarChart></ResponsiveContainer></ChartBox><ChartBox title="Violations over time"><ResponsiveContainer width="100%" height="100%"><LineChart data={analytics.overTime}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="time" stroke="var(--muted-foreground)" fontSize={11}/><YAxis stroke="var(--muted-foreground)" fontSize={11}/><Tooltip contentStyle={tip}/><Line dataKey="incidents" stroke="var(--primary)" strokeWidth={2} dot={{fill:"var(--primary)",r:3}}/></LineChart></ResponsiveContainer></ChartBox><ChartBox title="Severity distribution"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={analytics.bySeverity} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88} paddingAngle={2}>{["var(--critical)","var(--warning)","var(--primary)","var(--chart-5)"].map((fill)=><Cell key={fill} fill={fill}/>)}</Pie><Tooltip contentStyle={tip}/></PieChart></ResponsiveContainer></ChartBox><ChartBox title="Daily incidents"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.daily}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="day" stroke="var(--muted-foreground)" fontSize={11}/><YAxis stroke="var(--muted-foreground)" fontSize={11}/><Tooltip contentStyle={tip}/><Bar dataKey="incidents" fill="var(--primary)" radius={[2,2,0,0]}/></BarChart></ResponsiveContainer></ChartBox><ChartBox title="Weekly incidents"><ResponsiveContainer width="100%" height="100%"><LineChart data={analytics.weekly}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="week" stroke="var(--muted-foreground)" fontSize={11}/><YAxis stroke="var(--muted-foreground)" fontSize={11}/><Tooltip contentStyle={tip}/><Line dataKey="incidents" stroke="var(--warning)" strokeWidth={2}/></LineChart></ResponsiveContainer></ChartBox></div></AppShell>}