import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Smartphone, WifiOff } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { EmptyState, FeedPlaceholder, MetricCard, PageHeader, Section, StatusBadge } from "@/components/common";
import { IncidentTable } from "@/components/data-table";
import { Button } from "@/components/ui/button";
import { cameras } from "@/mock/cameras";
import { incidents } from "@/mock/incidents";

export const Route = createFileRoute("/cameras/$id")({ head: ({ params }) => ({ meta: [{ title: `${params.id} — Camera Detail` }, { name: "description", content: "Camera connection, monitoring placeholder, and recent incidents." }, { property: "og:title", content: `${params.id} — Camera Detail` }, { property: "og:description", content: "Traffic camera status and recent incident record." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: CameraDetail });
function CameraDetail() { const { id } = Route.useParams(); const camera = cameras.find((item) => item.id === id); if (!camera) return <AppShell><EmptyState title="Camera not found" description="This camera ID is not present in the demonstration registry." /></AppShell>; const recent = incidents.filter((incident) => incident.cameraId === id); return <AppShell><PageHeader title={`${camera.id} · ${camera.name}`} description={camera.location} actions={<Button asChild variant="outline" size="sm"><Link to="/cameras"><ArrowLeft />All cameras</Link></Button>} /><div className="grid gap-3 sm:grid-cols-4"><MetricCard label="Status" value={camera.status.toUpperCase()} detail="Latest registered state" tone={camera.status === "online" ? "success" : "warning"} /><MetricCard label="Mode" value={camera.mode.toUpperCase()} detail={camera.currentDemoId ?? "No active scenario"} /><MetricCard label="Incidents" value={recent.length} detail="Linked demo records" /><MetricCard label="Heartbeat" value={camera.lastHeartbeat ? new Date(camera.lastHeartbeat).toLocaleTimeString() : "—"} detail="Last device contact" /></div><Section title="Camera feed" description="No live CCTV stream is connected"><FeedPlaceholder camera={camera} large /></Section><div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><Section title="Recent incidents">{recent.length ? <IncidentTable incidents={recent} compact /> : <EmptyState title="No recent incidents" description="No demo incidents are linked to this camera." />}</Section><Section title="Connection information" description="Future Android CCTV registration"><div className="space-y-4 p-4"><div className="flex items-center gap-3"><Smartphone className="h-5 w-5 text-muted-foreground"/><div className="flex-1"><p className="text-sm font-medium">Android camera device</p><p className="font-mono text-xs text-muted-foreground">{camera.androidDeviceId ?? "Not registered"}</p></div><StatusBadge value={camera.androidDeviceId ? "registered" : "offline"}/></div><div className="flex items-center gap-3"><WifiOff className="h-5 w-5 text-warning"/><div className="flex-1"><p className="text-sm font-medium">Live transport</p><p className="text-xs text-muted-foreground">Awaiting future WebSocket/API connection</p></div><StatusBadge value="disconnected"/></div></div></Section></div></AppShell>; }