import { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Activity, Play, Radio, Server, WifiOff } from "lucide-react";
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip } from "recharts";
import { toast } from "sonner";
import { AppShell } from "@/components/app-shell";
import { ConnectionStrip, FeedPlaceholder, MetricCard, PageHeader, Section, SeverityBadge, StatusBadge } from "@/components/common";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { cameras } from "@/mock/cameras";
import { analytics } from "@/mock/analytics";
import { useAppState } from "@/state/app-state";
import { websocketService } from "@/services/websocketService";

export const Route = createFileRoute("/dashboard")({ head: () => ({ meta: [{ title: "Dashboard — Nepal Traffic Monitor" }, { name: "description", content: "Operational overview for camera status and traffic violation incidents." }, { property: "og:title", content: "Traffic Operations Dashboard" }, { property: "og:description", content: "Operational camera and incident monitoring dashboard." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Dashboard });
function Dashboard() { const { incidents, addIncident } = useAppState(); const [violationFilter, setViolationFilter] = useState("All"); function simulate() { const event = websocketService.simulateIncident(); if (!event) return; addIncident(event); toast.warning("Demo violation event", { description: `${event.violation} · ${event.cameraId} · ${event.licensePlate}` }); }
const weeklyViolations = analytics.weekly.at(-1)?.incidents ?? 0;
const recentIncidents = incidents.filter((incident) => violationFilter === "All" || incident.violation === violationFilter);
return <AppShell><PageHeader title="Operational Dashboard" description="Camera health, incidents, and simulated monitoring activity." actions={<Button size="sm" onClick={simulate}><Play />Simulate demo incident</Button>} /><ConnectionStrip /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-2"><MetricCard label="Today's violations" value={148 + Math.max(0, incidents.length - 8)} detail="Demo dataset" /><MetricCard label="Weekly violations" value={weeklyViolations} detail="Last reported week" tone="warning" /></div><div className="grid gap-5 xl:grid-cols-[1.65fr_1fr]"><Section title="Camera monitoring" description="Static placeholders — no live video connection"><div className="grid gap-px bg-border"><FeedPlaceholder key={cameras[0].id} camera={cameras[0]} large /></div></Section><Section title="Recent incidents" description="Demo event stream" action={<Select value={violationFilter} onValueChange={setViolationFilter}><SelectTrigger className="w-44"><SelectValue placeholder="Violation type" /></SelectTrigger><SelectContent><SelectItem value="All">All violations</SelectItem><SelectItem value="Signal Jumping">Signal Jumping</SelectItem><SelectItem value="Overspeeding">Overspeeding</SelectItem><SelectItem value="Helmetless Riding">Helmetless Riding</SelectItem><SelectItem value="Wrong Lane">Wrong Lane</SelectItem><SelectItem value="Triple Riding">Triple Riding</SelectItem></SelectContent></Select>}><div className="max-h-[420px] min-h-[420px] overflow-y-auto divide-y divide-border">{recentIncidents.length ? recentIncidents.map((incident) => <div key={incident.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold">{incident.violation}</p><p className="mt-1 font-mono text-xs text-muted-foreground">{incident.cameraId} · {incident.licensePlate}</p></div><SeverityBadge severity={incident.severity} /></div><div className="mt-3 flex items-center justify-between text-[11px] text-muted-foreground"><span>-</span><span>{new Date(incident.detectedAt).toLocaleTimeString()}</span></div></div>) : <div className="p-4 text-sm text-muted-foreground">No incidents found for this filter.</div>}</div></Section></div></AppShell>; }