import { useMemo, useState } from "react";
import { createFileRoute, Outlet, useRouterState } from "@tanstack/react-router";
import { AppShell } from "@/components/app-shell";
import { IncidentTable, PaginationBar } from "@/components/data-table";
import { EmptyState, PageHeader, SearchField, Section } from "@/components/common";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useAppState } from "@/state/app-state";

export const Route = createFileRoute("/incidents")({ head: () => ({ meta: [{ title: "Incidents — Nepal Traffic Monitor" }, { name: "description", content: "Search, filter, and review traffic violation incident records." }, { property: "og:title", content: "Traffic Incident Management" }, { property: "og:description", content: "Search and review traffic violation incident records." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: IncidentsPage });
function IncidentsPage() { const { incidents, deleteIncident } = useAppState(); const hasDetail = useRouterState({ select: (state) => state.matches.some((match) => match.routeId === "/incidents/$id") }); const [query,setQuery]=useState(""); const [severity,setSeverity]=useState("all"); const [status,setStatus]=useState("all"); const [violation,setViolation]=useState("all"); const [page,setPage]=useState(1); const filtered=useMemo(()=>incidents.filter((i)=>(severity==="all"||i.severity===severity)&&(status==="all"||i.status===status)&&(violation==="all"||i.violation===violation)&&`${i.id} ${i.cameraId} ${i.violation} ${i.licensePlate} ${i.location}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>new Date(b.createdAt??b.detectedAt).getTime()-new Date(a.createdAt??a.detectedAt).getTime()),[incidents,query,severity,status,violation]); const pageSize=6; const pages=Math.max(1,Math.ceil(filtered.length/pageSize)); const rows=filtered.slice((page-1)*pageSize,page*pageSize); const filter=(value:string,set:(v:string)=>void,items:string[],label:string)=><Select value={value} onValueChange={(v)=>{set(v);setPage(1)}}><SelectTrigger className="w-36"><SelectValue placeholder={label}/></SelectTrigger><SelectContent><SelectItem value="all">All {label}</SelectItem>{items.map((i)=><SelectItem key={i} value={i}>{i}</SelectItem>)}</SelectContent></Select>;
if (hasDetail) return <Outlet />;
return <AppShell><PageHeader title="Incidents" description="Violation review queue with evidence and operational status."/><Section title="Incident registry" description={`${filtered.length} matching records`} action={<SearchField value={query} onChange={setQuery} placeholder="Search incidents"/>}><div className="flex flex-wrap gap-2 border-b border-border p-3">{filter(violation,setViolation,["Signal Jumping","Overspeeding","Helmetless Riding","Wrong Lane","Triple Riding","No Helmet & Triple Riding"],"violations")}{filter(severity,setSeverity,["critical","high","medium","low"],"severities")}{filter(status,setStatus,["new","pending","reviewing","resolved"],"statuses")}</div>{rows.length?<IncidentTable incidents={rows} onDelete={(id)=>void deleteIncident(id)}/>:<EmptyState title="No incidents found" description="Adjust the search or filter selection."/>}<PaginationBar page={Math.min(page,pages)} pages={pages} onPage={setPage}/></Section></AppShell>; }