import { useEffect, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Eye, EyeOff, ShieldCheck } from "lucide-react";
import { onAuthStateChanged } from "firebase/auth";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getFirebaseClient } from "@/backend/firebaseClient";
import { authService } from "@/services/authService";

export const Route = createFileRoute("/login")({ head: () => ({ meta: [{ title: "Sign in — Nepal Traffic Monitor" }, { name: "description", content: "Sign in to the traffic monitoring control room." }, { property: "og:title", content: "Sign in — Nepal Traffic Monitor" }, { property: "og:description", content: "Secure frontend access to the traffic monitoring dashboard." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: LoginPage });

function LoginPage() { const navigate = useNavigate({ from: "/login" }); const [email, setEmail] = useState("operator@traffic.gov.np"); const [password, setPassword] = useState("demopassword"); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); useEffect(() => { const client = getFirebaseClient(); if (!client) return; return onAuthStateChanged(client.auth, (user) => { if (user) void authService.logout(); }); }, []); async function submit(event: React.FormEvent) { event.preventDefault(); if (!email.includes("@") || password.length < 8) { toast.error("Enter a valid email and password"); return; } setLoading(true); try { await authService.login(email, password); toast.success("Signed in"); await navigate({ to: "/dashboard" }); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to sign in"); } finally { setLoading(false); } }
  return <main className="grid min-h-screen bg-background lg:grid-cols-[0.9fr_1.1fr]"><section className="hidden border-r border-border bg-sidebar p-12 lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-sm bg-primary text-primary-foreground"><ShieldCheck className="h-5 w-5" /></div><div><p className="font-semibold">Nepal Traffic Monitor</p><p className="text-xs text-muted-foreground">Traffic Control Room</p></div></div><div><p className="max-w-md text-3xl font-semibold leading-tight">Centralized traffic monitoring and violation management.</p><p className="mt-4 max-w-md text-sm leading-6 text-muted-foreground">Frontend demonstration environment. No live camera, backend, or enforcement system is connected.</p></div><p className="text-xs text-muted-foreground">Authorized personnel access · Demo environment</p></section><section className="flex items-center justify-center p-6"><form onSubmit={submit} className="w-full max-w-sm"><div className="mb-8 flex items-center gap-3 lg:hidden"><ShieldCheck className="h-6 w-6 text-primary" /><span className="font-semibold">Nepal Traffic Monitor</span></div><p className="text-xs font-semibold uppercase text-primary">Operator access</p><h1 className="mt-2 text-2xl font-semibold">Sign in to control room</h1><p className="mt-2 text-sm text-muted-foreground">Use the demo credentials shown below.</p><div className="mt-7 space-y-4"><div className="space-y-2"><Label htmlFor="email">Email</Label><Input id="email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></div><div className="space-y-2"><div className="flex justify-between"><Label htmlFor="password">Password</Label><button type="button" onClick={() => toast.info("Password recovery will connect to the future authentication service.")} className="text-xs text-primary hover:underline">Forgot password?</button></div><div className="relative"><Input id="password" type={show ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} required className="pr-10" /><Button type="button" variant="ghost" size="icon" aria-label="Toggle password visibility" onClick={() => setShow(!show)} className="absolute right-0 top-0">{show ? <EyeOff /> : <Eye />}</Button></div></div><label className="flex items-center gap-2 text-sm text-muted-foreground"><Checkbox />Remember this device</label><Button type="submit" className="w-full" disabled={loading}>{loading ? "Signing in…" : "Sign in"}</Button></div><p className="mt-6 text-center text-sm text-muted-foreground">Need an operator account? <Link to="/register" className="text-primary hover:underline">Register</Link></p></form></section></main>;
}