import { useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { authService } from "@/services/authService";

export const Route = createFileRoute("/register")({ head: () => ({ meta: [{ title: "Register — Nepal Traffic Monitor" }, { name: "description", content: "Create a demo operator profile for the traffic monitoring frontend." }, { property: "og:title", content: "Register — Nepal Traffic Monitor" }, { property: "og:description", content: "Create a demo operator profile for the monitoring dashboard." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: RegisterPage });
function RegisterPage() { const navigate = useNavigate({ from: "/register" }); const [role, setRole] = useState<"ADMIN" | "OPERATOR">("OPERATOR"); async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const password = String(data.get("password")); const confirm = String(data.get("confirm")); if (password.length < 8 || password !== confirm) { toast.error("Passwords must match and contain at least 8 characters"); return; } try { await authService.register(String(data.get("name")), String(data.get("email")), role, password); toast.success("Profile created"); await navigate({ to: "/dashboard" }); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to create account"); } }
return <main className="flex min-h-screen items-center justify-center bg-background p-6"><form onSubmit={submit} className="w-full max-w-lg border border-border bg-card p-6 sm:p-8"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-primary" /><div><p className="font-semibold">Nepal Traffic Monitor</p><p className="text-xs text-muted-foreground">Frontend demonstration registration</p></div></div><h1 className="mt-8 text-2xl font-semibold">Create operator profile</h1><p className="mt-2 text-sm text-muted-foreground">This creates an in-memory demo profile only. No account is stored.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="space-y-2 sm:col-span-2"><Label htmlFor="name">Full name</Label><Input id="name" name="name" required /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="reg-email">Email</Label><Input id="reg-email" name="email" type="email" required /></div><div className="space-y-2"><Label htmlFor="reg-password">Password</Label><Input id="reg-password" name="password" type="password" minLength={8} required /></div><div className="space-y-2"><Label htmlFor="confirm">Confirm password</Label><Input id="confirm" name="confirm" type="password" minLength={8} required /></div><div className="space-y-2 sm:col-span-2"><Label>Role</Label><Select value={role} onValueChange={(value) => setRole(value === "ADMIN" ? "ADMIN" : "OPERATOR")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="OPERATOR">Operator</SelectItem><SelectItem value="ADMIN">Administrator</SelectItem></SelectContent></Select></div></div><Button type="submit" className="mt-6 w-full">Create demo profile</Button><p className="mt-5 text-center text-sm text-muted-foreground">Already registered? <Link to="/login" className="text-primary hover:underline">Sign in</Link></p></form></main>; }