import { useState } from "react";
import { Link, useRouterState } from "@tanstack/react-router";
import { Activity, BarChart3, ChevronLeft, FolderOpen, Gauge, LogOut, Menu, ShieldCheck, Upload, WifiOff } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

const items = [
  { label: "Dashboard", to: "/dashboard", icon: Gauge },
  { label: "Incidents", to: "/incidents", icon: Activity },
  { label: "Evidence", to: "/evidence", icon: FolderOpen },
  { label: "Upload videos", to: "/upload", icon: Upload },
  { label: "Analytics", to: "/analytics", icon: BarChart3 },
] as const;

const titles: Record<string, string> = { dashboard: "Operational Dashboard", incidents: "Incident Management", evidence: "Evidence Registry", upload: "Upload Videos", analytics: "Traffic Analytics" };

export function AppShell({ children }: { children: React.ReactNode }) {
  const [collapsed, setCollapsed] = useState(false); const [mobile, setMobile] = useState(false);
  const pathname = useRouterState({ select: (state) => state.location.pathname });
  const segment = pathname.split("/")[1] || "dashboard"; const pageTitle = titles[segment] ?? "Traffic Monitoring";
  const sidebar = <div className="flex h-full flex-col"><div className="flex h-16 items-center gap-3 border-b border-sidebar-border px-4"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-sm bg-sidebar-primary text-sidebar-primary-foreground"><ShieldCheck className="h-4 w-4" /></div>{!collapsed && <div className="min-w-0"><p className="truncate text-sm font-semibold">TriNetra</p><p className="text-[10px] uppercase text-muted-foreground">Control Room</p></div>}</div><nav className="flex-1 space-y-1 p-2">{items.map((item) => { const active = pathname === item.to || pathname.startsWith(`${item.to}/`); return <Tooltip key={item.to}><TooltipTrigger asChild><Link to={item.to} onClick={() => setMobile(false)} className={cn("flex h-10 items-center gap-3 rounded-sm px-3 text-sm text-sidebar-foreground/70 transition-colors hover:bg-sidebar-accent hover:text-sidebar-accent-foreground", active && "bg-sidebar-accent text-sidebar-primary")}><item.icon className="h-4 w-4 shrink-0" />{!collapsed && <span>{item.label}</span>}</Link></TooltipTrigger>{collapsed && <TooltipContent side="right">{item.label}</TooltipContent>}</Tooltip>; })}</nav><div className="border-t border-sidebar-border p-3">{!collapsed && <div className="mb-3 flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-secondary text-xs font-semibold">SS</div><div className="min-w-0"><p className="truncate text-xs font-medium">Suman Shrestha</p><p className="text-[10px] text-muted-foreground">ADMIN · Demo session</p></div></div>}<Button asChild variant="ghost" size={collapsed ? "icon" : "sm"} className={cn("text-muted-foreground", !collapsed && "w-full justify-start")}><Link to="/login"><LogOut />{!collapsed && "Logout"}</Link></Button></div></div>;
  return <TooltipProvider><div className="min-h-screen bg-background"><aside className={cn("fixed inset-y-0 left-0 z-40 hidden border-r border-sidebar-border bg-sidebar transition-[width] lg:block", collapsed ? "w-16" : "w-60")}>{sidebar}<Button variant="outline" size="icon" aria-label="Toggle sidebar" onClick={() => setCollapsed(!collapsed)} className="absolute -right-4 top-20 h-8 w-8 rounded-full"><ChevronLeft className={cn("transition-transform", collapsed && "rotate-180")} /></Button></aside>{mobile && <><button aria-label="Close navigation" onClick={() => setMobile(false)} className="fixed inset-0 z-40 bg-background/80 lg:hidden" /><aside className="fixed inset-y-0 left-0 z-50 w-72 border-r border-sidebar-border bg-sidebar lg:hidden">{sidebar}</aside></>}<div className={cn("transition-[padding]", collapsed ? "lg:pl-16" : "lg:pl-60")}><header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b border-border bg-background/95 px-4 backdrop-blur sm:px-6"><Button variant="ghost" size="icon" aria-label="Open navigation" onClick={() => setMobile(true)} className="lg:hidden"><Menu /></Button><div><p className="text-sm font-semibold">{pageTitle}</p><p className="hidden text-[11px] text-muted-foreground sm:block">Operations / {pageTitle}</p></div><div className="ml-auto flex items-center gap-4"><div className="hidden items-center gap-2 text-xs text-muted-foreground md:flex"><WifiOff className="h-3.5 w-3.5 text-warning" />WebSocket disconnected</div><div className="flex items-center gap-2 border-l border-border pl-4"><span className="h-2 w-2 rounded-full bg-warning" /><span className="hidden text-[11px] font-semibold uppercase sm:inline">Development mode</span></div><div className="flex h-8 w-8 items-center justify-center rounded-full bg-secondary text-xs font-semibold">SS</div></div></header><main className="mx-auto max-w-[1600px] space-y-5 p-4 sm:p-6">{children}</main></div></div></TooltipProvider>;
}