import { Link } from "@tanstack/react-router";
import { ArrowUpDown, ChevronLeft, ChevronRight, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { SeverityBadge, StatusBadge } from "@/components/common";
import type { Incident } from "@/types";

export function IncidentTable({ incidents, compact = false, onDelete }: { incidents: Incident[]; compact?: boolean; onDelete?: (id: string) => void }) {
  return <Table><TableHeader><TableRow><TableHead>Incident</TableHead><TableHead>Camera</TableHead><TableHead>Violation</TableHead>{!compact && <><TableHead>Vehicle</TableHead><TableHead>License plate</TableHead><TableHead>Speed</TableHead></>}{!compact && <TableHead>Location</TableHead>}<TableHead>Severity</TableHead><TableHead>Status</TableHead>{!compact && <><TableHead>Evidence</TableHead><TableHead className="text-right"><span className="inline-flex items-center gap-1">Created <ArrowUpDown className="h-3 w-3" /></span></TableHead>{onDelete && <TableHead />}</>}</TableRow></TableHeader><TableBody>{incidents.map((incident) => <TableRow key={incident.id}><TableCell><Link to="/incidents/$id" params={{ id: incident.id }} className="font-mono text-xs font-semibold text-primary hover:underline">{incident.id}</Link></TableCell><TableCell className="font-mono text-xs">{incident.cameraId}</TableCell><TableCell className="whitespace-nowrap font-medium">{incident.violation}</TableCell>{!compact && <><TableCell className="font-mono text-xs">{incident.vehicleId}</TableCell><TableCell className="whitespace-nowrap font-mono text-xs">{incident.licensePlate}</TableCell><TableCell>{incident.speed === null ? "-" : `${incident.speed} km/h`}</TableCell></>}{!compact && <TableCell className="whitespace-nowrap">-</TableCell>}<TableCell><SeverityBadge severity={incident.severity} /></TableCell><TableCell><StatusBadge value={incident.status} /></TableCell>{!compact && <><TableCell className="font-mono text-xs">{incident.evidenceId}</TableCell><TableCell className="whitespace-nowrap text-right text-xs text-muted-foreground">{new Date(incident.createdAt??incident.detectedAt).toLocaleString()}</TableCell>{onDelete && <TableCell><Button type="button" variant="ghost" size="icon" aria-label={`Delete ${incident.id}`} onClick={()=>onDelete(incident.id)}><Trash2/></Button></TableCell>}</>}</TableRow>)}</TableBody></Table>;
}

export function PaginationBar({ page, pages, onPage }: { page: number; pages: number; onPage: (page: number) => void }) { return <div className="flex items-center justify-between border-t border-border px-4 py-3"><p className="text-xs text-muted-foreground">Page {page} of {pages}</p><div className="flex gap-2"><Button size="icon" variant="outline" disabled={page === 1} onClick={() => onPage(page - 1)} aria-label="Previous page"><ChevronLeft /></Button><Button size="icon" variant="outline" disabled={page === pages} onClick={() => onPage(page + 1)} aria-label="Next page"><ChevronRight /></Button></div></div>; }