/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as CamerasIdRouteImport } from './routes/cameras.$id'
import { Route as DemoLibraryIdRouteImport } from './routes/demo-library.$id'
import { Route as IncidentsIdRouteImport } from './routes/incidents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CamerasIdRoute = CamerasIdRouteImport.update({
  id: '/cameras/$id',
  path: '/cameras/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLibraryIdRoute = DemoLibraryIdRouteImport.update({
  id: '/demo-library/$id',
  path: '/demo-library/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdRoute = IncidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IncidentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/cameras/$id': typeof CamerasIdRoute
  '/demo-library/$id': typeof DemoLibraryIdRoute
  '/incidents/$id': typeof IncidentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/cameras/$id': typeof CamerasIdRoute
  '/demo-library/$id': typeof DemoLibraryIdRoute
  '/incidents/$id': typeof IncidentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/incidents': typeof IncidentsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/cameras/$id': typeof CamerasIdRoute
  '/demo-library/$id': typeof DemoLibraryIdRoute
  '/incidents/$id': typeof IncidentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/evidence'
    | '/incidents'
    | '/login'
    | '/register'
    | '/upload'
    | '/cameras/$id'
    | '/demo-library/$id'
    | '/incidents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/evidence'
    | '/incidents'
    | '/login'
    | '/register'
    | '/upload'
    | '/cameras/$id'
    | '/demo-library/$id'
    | '/incidents/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/evidence'
    | '/incidents'
    | '/login'
    | '/register'
    | '/upload'
    | '/cameras/$id'
    | '/demo-library/$id'
    | '/incidents/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  EvidenceRoute: typeof EvidenceRoute
  IncidentsRoute: typeof IncidentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UploadRoute: typeof UploadRoute
  CamerasIdRoute: typeof CamerasIdRoute
  DemoLibraryIdRoute: typeof DemoLibraryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cameras/$id': {
      id: '/cameras/$id'
      path: '/cameras/$id'
      fullPath: '/cameras/$id'
      preLoaderRoute: typeof CamerasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-library/$id': {
      id: '/demo-library/$id'
      path: '/demo-library/$id'
      fullPath: '/demo-library/$id'
      preLoaderRoute: typeof DemoLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id': {
      id: '/incidents/$id'
      path: '/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof IncidentsIdRouteImport
      parentRoute: typeof IncidentsRoute
    }
  }
}

interface IncidentsRouteChildren {
  IncidentsIdRoute: typeof IncidentsIdRoute
}

const IncidentsRouteChildren: IncidentsRouteChildren = {
  IncidentsIdRoute: IncidentsIdRoute,
}

const IncidentsRouteWithChildren = IncidentsRoute._addFileChildren(
  IncidentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  EvidenceRoute: EvidenceRoute,
  IncidentsRoute: IncidentsRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UploadRoute: UploadRoute,
  CamerasIdRoute: CamerasIdRoute,
  DemoLibraryIdRoute: DemoLibraryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
